"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup

APP = ['tunnels.py']
DATA_FILES = ['config_template.yaml', 'resources']
OPTIONS = {
    'packages': ['rumps'],
    'iconfile':'tunnel.icns',
    'plist': {
        'CFBundleShortVersionString':'0.1.0',
        'LSUIElement': True
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
